set-option -g default-terminal 'xterm-256color'
set -ga terminal-overrides ",*256col*:Tc"
set -qg utf8
set-window-option -qg utf8 on
set-environment -g COLORTERM truecolor
set-option -g set-titles on
set-option -g set-titles-string '#T'
set-option -g prefix C-a
unbind-key C-b
bind-key   a send-prefix
set-option -g status off
set-option -g escape-time 1
bind-key n next-window
bind-key C-a last-window
bind-key C-n next-window
bind-key p previous-window
bind-key C-p previous-window
bind-key c new-window
bind-key C-c new-window
bind-key C-d detach-client
bind-key k kill-window
bind-key C-k kill-window
bind-key \\  kill-session
unbind-key t
bind-key C-t new-window
bind-key t   new-window
list_windows='[ -n "$WSL_DISTRO_NAME" ] && tmux display-message "`tmux list-windows -F "##I: ##{s/[.](exe|cmd|bat).*$//:##{?##{==:##{b:pane_current_command},init},##{b:pane_start_command},##{b:pane_current_command}}}##{window_active}  " | sed "s/0  $/  /; s/1  $/*  /"`" || tmux display-message "`tmux list-windows -F "##I: ##{s/[.](exe|cmd|bat).*$//:##{b:pane_current_command}}##{window_active}  " | sed "s/0  $/  /; s/1  $/*  /"`"'

bind-key w   run-shell $list_windows
bind-key C-w run-shell $list_windows
run 'unset list_windows'

set-window-option -g mode-keys vi

set-option -ag message-style "fg=black,bg=brightwhite"

bind-key Escape copy-mode

# Add shift-page<up/down> bindings for scrolling.
bind-key -T root         -n S-PPage copy-mode -u
bind-key -T copy-mode-vi -n S-PPage send-keys -X page-up
bind-key -T copy-mode-vi -n S-NPage send-keys -X page-down

# Increase copy-mode buffer size.
set-option -g history-limit 300000
